name: on-push
on: [push, pull_request]
env:
  MIX_ENV: test
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ["23.3.3", "24.1.1"]
        elixir: ["1.10.4", "1.11.4", "1.12.2"]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Mix dependencies cache
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - run: mix deps.get
      - run: mix format --check-formatted
        if: matrix.elixir == '1.12.2' # Only check formatting with the latest version
      - run: mix compile --warnings-as-errors
      - run: mix test
      - run: mix dialyzer
        if: matrix.elixir == '1.12.2' # Only check dialyzer with the latest version
